# Generated by Django 3.0.5 on 2020-05-05 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battleshipServer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guestField',
            new_name='hostEnemyField',
        ),
    ]
